apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sdebackend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: sdebackend.dns-test-cluster
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sdebackend  # Ensure this matches your service name
            port:
              number: 8080
